# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Landon Holcomb - PhD student in Computer Science at Clemson University. Research in quantum computing, quantum machine learning, and quantum algorithms.'
    twitter: ''
  analytics:
    google_analytics: ''  # Add your GA4 measurement ID here (e.g., 'G-XXXXXXXXXX')
    baidu_tongji: ''
    plausible: ''  # Add your Plausible domain here if using Plausible Analytics
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    block: 'navbar'
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: 'Landon Holcomb'

# Site footer
footer:
  copyright:
    notice: '© {year} Landon Holcomb'
    license:
      enable: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true  # Enable LaTeX math rendering for quantum equations
  privacy_pack:
    enable: false
